services:
  monitor:
    build: .
    container_name: bkpprovider_monitor
    restart: always
    environment:
      - TZ=America/Recife
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-@Jeff2712}
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./main.py:/app/main.py
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      - /etc/localtime:/etc/localtime:ro

    cap_add:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - default

  nginx:
    build: ./nginx
    container_name: bkpprovider_nginx
    restart: always
    environment:
      - TZ=America/Recife
    ports:
      - "8081:80"
      - "4443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - monitor

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    networks:
      - default
      - web_net

networks:
  default:
  web_net:
    external: true



